layout_spectrum: 0.1863799
typography_spectrum: 0.4444444
color:
  saturation: 0.6953405
  brandStrength: 0.4678007
  lightness: 0.07885305
  rhythmicContrast: 0.5784405
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: DONOVAN. Strategic Communications
